### ISSUE TITLE
Getting build error

### ISSUE THREAD

**Issue by Pranab16** [theKashey/react-focus-lock#144]
I am getting below error when building the app. Please help

```
/home/test/app/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js:1
export default function _objectWithoutPropertiesLoose(source, excluded) {
^^^^^^
SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@babel/runtime/helpers/esm/objectWithoutPropertiesLoose (/home/test/app/dist/main.index.server.js:157301:18)
    at __webpack_require__ (/home/test/app/dist/main.index.server.js:27:30)
    at Object../node_modules/react-focus-lock/dist/es2015/Combination.js (/home/test/app/dist/main.index.server.js:105174:61)
    at __webpack_require__ (/home/test/app/dist/main.index.server.js:27:30
```
    
    
Using below `babel.config.js`
```
module.exports = function (api) {
  api.cache(true);

  return {
    "presets": [
      [
        "@babel/preset-env",
        {
          "modules": "commonjs",
          "targets": {
            "browsers": ["last 2 versions", "ie >= 10", "Firefox ESR"],
            "node": "current"
          },
          // forceAllTransforms: api.env('production'), //https://babeljs.io/docs/en/babel-preset-env#forcealltransforms
          "useBuiltIns": "entry",
          // corejs: { version: 3, proposals: true }
          "corejs": "3.0.0"
        }
      ],
      "@babel/preset-react",
      "@babel/preset-typescript"
    ],
    "plugins": [
      "emotion",
      "lodash",
      "@babel/plugin-proposal-optional-chaining",
      "@babel/plugin-proposal-nullish-coalescing-operator",
      // "add-module-exports",
      "@babel/plugin-transform-runtime",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-syntax-import-meta",
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ],
      // "dynamic-import-node",
      "@babel/plugin-proposal-function-sent",
      "@babel/plugin-proposal-export-default-from",
      "@babel/plugin-proposal-export-namespace-from",
      "@babel/plugin-proposal-numeric-separator",
      "@babel/plugin-proposal-throw-expressions",
      [
        "@babel/plugin-proposal-class-properties",
        {
          "loose": false
        }
      ],
      "@babel/plugin-proposal-json-strings",
      "@babel/plugin-proposal-private-methods",
      "@babel/plugin-transform-react-inline-elements",
      [
        "@babel/plugin-transform-template-literals",
        {
          "loose": true
        }
      ],

      // "syntax-dynamic-import",
      [
        "react-loadable/babel",
        {
          "serverSideRequirePath": true,
          "webpackRequireWeakId": true
        }
      ]
      // "transform-class-properties",
      // "transform-object-rest-spread",
      // "transform-export-extensions",
      // "transform-proto-to-assign",
      // "transform-decorators-legacy",
      // "transform-runtime"
    ],
    "env": {
      "production": {
        "plugins": ["emotion", "transform-react-remove-prop-types"]
      },
      "test": {
        "plugins": ["istanbul"]
      }
    }
  };
}
```

**Comment by theKashey** [comment]
That is not related to babel, but to webpack settings expecting something else from your code.
Try starting from 
```diff
- "modules": "commonjs",`
+ "modules": false,
```
