### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by elliottsj** [theKashey/react-focus-lock#59]
I started getting this error in version 1.18.2:

```
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/spencerelliott/Dev/path/to/common/temp/node_modules/.registry.npmjs.org/react-focus-lock/1.18.2/react@16.8.4/node_modules/react-focus-lock/dist/cjs/Lock.js:195:44)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/spencerelliott/Dev/path/to/common/temp/node_modules/.registry.npmjs.org/react-focus-lock/1.18.2/react@16.8.4/node_modules/react-focus-lock/dist/cjs/index.js:34:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

I think it was introduced in this commit: https://github.com/theKashey/react-focus-lock/commit/7bc46f0f81255455238999f56bf001c5c83797ea#diff-757809db6137e7d28cf62c382a00aeadR147

**Comment by theKashey** [comment]
🤷‍♂️all tests are green 🤷‍♂️

**Comment by theKashey** [comment]
Ok, so the question is - what your browser? `Element` is defined for me as `window.Element`

**Comment by theKashey** [comment]
I've just made it `any`. Anyway - I don't believe in prop types, almost all IDEs could use d.ts.
Try 1.18.3

**Comment by elliottsj** [comment]
Ah, I'm realizing now that the error was occurring since I'm using Next.js, and of course `window.Element` is not defined in Node.js when server-side rendering.

**Comment by theKashey** [comment]
Got it, so my `jsdom/register`, I am using for tests, was letting them pass.
